In [1]:
from yelpapi import YelpAPI
import json
import pandas as pd

In [2]:
import json
with open('/Users/12103/.secret/yelp_api.json') as f:
    login = json.load(f)
login.keys()

dict_keys(['client-id', 'api-key'])

In [3]:
# import the YelpAPI Class
from yelpapi import YelpAPI
# Create an instance with your key
yelp_api = YelpAPI(login['api-key'], timeout_s=5.0)
yelp_api

In [10]:
# use our yelp_api variable's search_query method to perform our API call
search_results = yelp_api.search_query(location='NY, NY',
                                       term='Pizza')
print(type(search_results))
search_results.keys()

<class 'dict'>

dict_keys(['businesses', 'total', 'region'])

In [11]:
search_results['total']

12400

In [12]:
biz = pd.DataFrame(search_results['businesses'])
biz.head(2)

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,price,location,phone,display_phone,distance
0,ysqgdbSrezXgVwER2kQWKA,julianas-brooklyn-3,Juliana's,https://s3-media2.fl.yelpcdn.com/bphoto/od36nF...,False,https://www.yelp.com/biz/julianas-brooklyn-3?a...,2722,"[{'alias': 'pizza', 'title': 'Pizza'}]",4.5,"{'latitude': 40.70274718768062, 'longitude': -...",[delivery],$$,"{'address1': '19 Old Fulton St', 'address2': '...",+17185966700,(718) 596-6700,308.569844
1,zj8Lq1T8KIC5zwFief15jg,prince-street-pizza-new-york-2,Prince Street Pizza,https://s3-media1.fl.yelpcdn.com/bphoto/2-U43P...,False,https://www.yelp.com/biz/prince-street-pizza-n...,5124,"[{'alias': 'pizza', 'title': 'Pizza'}, {'alias...",4.5,"{'latitude': 40.72308755605564, 'longitude': -...","[pickup, delivery]",$,"{'address1': '27 Prince St', 'address2': None,...",+12129664100,(212) 966-4100,1961.877142

In [13]:
# add offset to our original api call
search_results = yelp_api.search_query(location='NY, NY',
                                       term='Pizza',
                                       offset = 20)

In [14]:
biz20 = pd.DataFrame(search_results['businesses'])
biz20.head(2)

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,price,location,phone,display_phone,distance
0,LF1QAuvpfX7KGQlg2zMg6Q,johns-of-bleecker-street-new-york-2,John's of Bleecker Street,https://s3-media1.fl.yelpcdn.com/bphoto/r2bmU0...,False,https://www.yelp.com/biz/johns-of-bleecker-str...,2679,"[{'alias': 'pizza', 'title': 'Pizza'}]",4.0,"{'latitude': 40.73158, 'longitude': -74.00332}","[pickup, delivery]",$$,"{'address1': '278 Bleecker St', 'address2': ''...",+12122431680,(212) 243-1680,3010.899021
1,hZBxJfZtDjnMzH_jNFNHRQ,little-pizza-parlor-brooklyn,Little Pizza Parlor,https://s3-media2.fl.yelpcdn.com/bphoto/99YkIi...,False,https://www.yelp.com/biz/little-pizza-parlor-b...,63,"[{'alias': 'pizza', 'title': 'Pizza'}]",4.5,"{'latitude': 40.692425, 'longitude': -73.984467}","[pickup, delivery]",NaN,"{'address1': '192 Duffield St', 'address2': No...",+13477991249,(347) 799-1249,1668.414104

In [15]:
## concatenate the previous results and new results. 
businesses = pd.concat([biz, biz20],
                      ignore_index=True)
display(businesses.head(3), businesses.tail(3))

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,price,location,phone,display_phone,distance
0,ysqgdbSrezXgVwER2kQWKA,julianas-brooklyn-3,Juliana's,https://s3-media2.fl.yelpcdn.com/bphoto/od36nF...,False,https://www.yelp.com/biz/julianas-brooklyn-3?a...,2722,"[{'alias': 'pizza', 'title': 'Pizza'}]",4.5,"{'latitude': 40.70274718768062, 'longitude': -...",[delivery],$$,"{'address1': '19 Old Fulton St', 'address2': '...",+17185966700,(718) 596-6700,308.569844
1,zj8Lq1T8KIC5zwFief15jg,prince-street-pizza-new-york-2,Prince Street Pizza,https://s3-media1.fl.yelpcdn.com/bphoto/2-U43P...,False,https://www.yelp.com/biz/prince-street-pizza-n...,5124,"[{'alias': 'pizza', 'title': 'Pizza'}, {'alias...",4.5,"{'latitude': 40.72308755605564, 'longitude': -...","[pickup, delivery]",$,"{'address1': '27 Prince St', 'address2': None,...",+12129664100,(212) 966-4100,1961.877142
2,WG639VkTjmK5dzydd1BBJA,rubirosa-new-york-2,Rubirosa,https://s3-media3.fl.yelpcdn.com/bphoto/l0Phrn...,False,https://www.yelp.com/biz/rubirosa-new-york-2?a...,3226,"[{'alias': 'italian', 'title': 'Italian'}, {'a...",4.5,"{'latitude': 40.722766, 'longitude': -73.996233}",[pickup],$$,"{'address1': '235 Mulberry St', 'address2': ''...",+12129650500,(212) 965-0500,1932.946770

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,price,location,phone,display_phone,distance
37,r1PWMTbFXBmEhi0scGPf3w,aces-pizza-brooklyn,Ace's Pizza,https://s3-media2.fl.yelpcdn.com/bphoto/id-UXj...,False,https://www.yelp.com/biz/aces-pizza-brooklyn?a...,175,"[{'alias': 'pizza', 'title': 'Pizza'}, {'alias...",4.5,"{'latitude': 40.71505, 'longitude': -73.958365}",[delivery],$$,"{'address1': '637 Driggs Ave', 'address2': '',...",+13477254366,(347) 725-4366,3210.927272
38,peV8B-MMMZb1mrC9r6rfAA,lucia-of-soho-new-york,Lucia of Soho,https://s3-media1.fl.yelpcdn.com/bphoto/xArz-6...,False,https://www.yelp.com/biz/lucia-of-soho-new-yor...,5,"[{'alias': 'pizza', 'title': 'Pizza'}]",5.0,"{'latitude': 40.721416405112784, 'longitude': ...","[pickup, delivery]",NaN,"{'address1': '375 Canal St', 'address2': None,...",,,1968.760493
39,2xQmBB6w-W6lxiex80fA9A,luigis-pizzeria-brooklyn-4,Luigi's Pizzeria,https://s3-media4.fl.yelpcdn.com/bphoto/j8wXRU...,False,https://www.yelp.com/biz/luigis-pizzeria-brook...,288,"[{'alias': 'pizza', 'title': 'Pizza'}]",4.5,"{'latitude': 40.6897, 'longitude': -73.965369}",[delivery],$,"{'address1': '326 Dekalb Ave', 'address2': '',...",+17187832430,(718) 783-2430,3001.831815

In [17]:
# save the results to records-style json file with appropriate name
businesses.to_json("Data/yelp-search-pizza-NY.json", orient='records')

In [ ]:
## concatenate the previous results and new results. 
pizza_businesses = pd.concat([biz, biz20],
                      ignore_index=True)
display(pizza_businesses.head(3), pizza_businesses.tail(3))